tasks:
- command: >
    echo '***********************************************************' ;
    echo '***** Maximize the terminal screen ************************' ;
    echo '***** then press return ***********************************' ;
    echo '***********************************************************' ;
    read ;
    cd /workspace/src/github.com/gbonacini/System-Invaders/ ;
    GOPATH=/workspace/src/github.com/gbonacini/System-Invaders/ go run src/main/main.go ;
    stty sane
  openIn: main
checkoutLocation: src/github.com/gbonacini/System-Invaders
workspaceLocation: src/github.com/gbonacini/System-Invaders